ERPSystem/Controllers/SuppliersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Common.Utilities;
using Domain.Entities;
using Domain.ViewModel.Transactions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;

namespace ERPSystem.Areas.Transactions.Controllers
{
    [Area("Transactions")]
    public class SuppliersController : Controller
    {
        [BindProperty]
        public SupplierViewModel AccCodeVM { get; set; }
        private readonly IConfiguration _config;
        public SuppliersController(IConfiguration config)
        {
            _config = config;
        }
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> Upsert(int? id)
        {
            AccCodeVM = new SupplierViewModel();
            ViewBag.AccountHeads = await DropDownData();
            if (id != null)
            {
                var AccCodes = await GetById((int)id);
                AccCodeVM.supp.SuppliersId = AccCodes.SuppliersId;
                AccCodeVM.supp.Address = AccCodes.Address;
                AccCodeVM.supp.Email = AccCodes.Email;
                AccCodeVM.supp.MobileNumber = AccCodes.MobileNumber;
                AccCodeVM.supp.Name = AccCodes.Name;
                AccCodeVM.supp.NtaxNumber = AccCodes.NtaxNumber;
            }

            return View(AccCodeVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert()
        {

            if (ModelState.IsValid)
            {
                Supplier accC = new Supplier();
                accC.SuppliersId = AccCodeVM.supp.SuppliersId;
                accC.Name = AccCodeVM.supp.Name;
                accC.Address = AccCodeVM.supp.Address;
                accC.Email = AccCodeVM.supp.Email;
                accC.MobileNumber = AccCodeVM.supp.MobileNumber;
                accC.NtaxNumber = AccCodeVM.supp.NtaxNumber;
                accC.IsActive = true;
                accC.created_at = DateTime.Now;
                if (AccCodeVM.supp.SuppliersId == 0)
                {
                    await Create(accC);
                }
                else
                {
                    await Update(accC);
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(AccCodeVM);
            }
        }
        #region API Calling

        
        [HttpPut]
        public async Task<IActionResult> Delete(int Id)
        {
            string apiUrl = _config["ServerAddress:Address"] + $"/api/v1/suppliers/{Id}";
            var res = await ApiCalls<Supplier>.Remove(apiUrl);
            return Json(new
            {
                data = res
            });
        }
        [HttpPost]
        public async Task<IActionResult> Create(Supplier accC)
        {
            string apiUrl = _config["ServerAddress:Address"] + $"/api/v1/suppliers/";
            var res = await ApiCalls<Supplier>.Add(accC, apiUrl);
            return Json(new
            {
                data = res
            });
        }
        [HttpPut]
        public async Task<IActionResult> Update(Supplier accH)
        {
            string apiUrl = _config["ServerAddress:Address"] + $"/api/v1/suppliers/update";
            var res = await ApiCalls<Supplier>.Update(accH, apiUrl);
            return Json(new
            {
                data = res
            });
        }

       
        #endregion
    }
}

ERPSystem/Areas/Transactions/Views/Suppliers /Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
<link href="~/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link href="~/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
<link href="~/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">

<div class="row">
    <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
            <div class="x_title">
                <h2>Suppliers </h2>
                <div class="btn-group float-right">
                    @*<a class="btn btn-primary nav-link text-white float-right" style="margin-bottom: 20px;" asp-area="Master" asp-controller="Items" asp-action="Upsert">New Item</a>*@
                    <button type="button" class="btn btn-primary newBtn" data-toggle="modal" data-target=".bs-example-modal-md" id="newItem">New Supplier</button>
                </div>
                <div class="clearfix"></div>

            </div>
            <div class="x_content">

                <div class="table-responsive">
                    <img src="~/images/loading.gif" style="
                            position: absolute;
                            top: 50px;
                            width: 100px;
                            left: 45%;
                    " />
                    <table id="tblData" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th>Sr #</th>
                                <th>Name</th>
                                <th>Mobile #</th>                              
                                <th>Action</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="~/vendors/jszip/dist/jszip.min.js"></script>
    <script src="~/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="~/vendors/pdfmake/build/vfs_fonts.js"></script>

    <script src="~/js/Transactions/Suppliers.js"></script>
}

ERPSystem/Areas/Transactions/Views/Suppliers /Upsert.cshtml
@model Domain.ViewModel.Transactions.SupplierViewModel
@{
    var title = (Model.supp.SuppliersId > 0) ? "Update" : "Save";
    title = title + "";
    ViewData["Title"] = title;

    Layout = null;// "~/Views/Shared/_Layout.cshtml";
}
<form asp-area="Transactions" asp-controller="Suppliers" asp-action="Upsert">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="form-group" hidden>
            <input asp-for="supp.SuppliersId" class="form-control" />
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label asp-for="supp.Name" class="control-label"></label>
                <input asp-for="supp.Name" class="form-control form-control-sm" />
                <span asp-validation-for="supp.Name" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label class="control-label">Mobile #</label>
                <input asp-for="supp.MobileNumber" class="form-control form-control-sm" />
                <span asp-validation-for="supp.MobileNumber" class="text-danger"></span>
            </div>       
    <div class="form-group float-right">
        <input type="submit" value="@title" class="btn btn-primary" />
        <input type="reset" value="Cancel" class="btn btn-danger" />
    </div>
</form>

<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.js"></script>