ERPSystem/Areas/Accounts/Controllers/DayOpeningsController.cs
using Application.Common.Utilities;
using Domain.Entities;
using Domain.ViewModel.Accounts;
using Domain.ViewModel.Reports;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ERPSystem.Areas.Accounts.Controllers //
{
    [Area("Accounts")]
    public class DayOpeningsController : Controller
    {
        [BindProperty]
        public DayOpeningsViewModel dayOpenVM { get; set; }
        private readonly IConfiguration _config;
        public DayOpeningsController(IConfiguration config)
        {
            _config = config;
        }
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
               [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert()
        {

            if (ModelState.IsValid)
            {
                DayOpenings dayOpen = new DayOpenings();
                
                if (dayOpenVM.dayopening.DayOpeningsId == 0)
                {
                    dayOpen.DateTimeOpening = dayOpenVM.dayopening.DateTimeOpening;
                    dayOpen.OpeningBalance = dayOpenVM.dayopening.OpeningBalance;
                    var res = await Create(dayOpen);
                    return Json(res);
                }
                else
                {
                    dayOpen.DayOpeningsId = dayOpenVM.dayopening.DayOpeningsId;
                    dayOpen.DateTimeClosing = dayOpenVM.dayopening.DateTimeClosing;
                    dayOpen.BankDeposit = dayOpenVM.dayopening.BankDeposit;
                    dayOpen.cashDifference = dayOpenVM.dayopening.cashDifference;
                    dayOpen.cashInHand = dayOpenVM.dayopening.cashInHand;
                    dayOpen.cashPayments = dayOpenVM.dayopening.cashPayments;
                    dayOpen.cashReciepts = dayOpenVM.dayopening.cashReciepts;
                    dayOpen.expenses = dayOpenVM.dayopening.expenses;
                    dayOpen.Notes = dayOpenVM.dayopening.Notes;
                    dayOpen.Purchases = dayOpenVM.dayopening.Purchases;
                    dayOpen.sales = dayOpenVM.dayopening.sales;
                    dayOpen.totalCash = dayOpenVM.dayopening.totalCash;
                    dayOpen.closeStatus = dayOpenVM.dayopening.closeStatus;
                    dayOpen.ClosingBalance = dayOpenVM.dayopening.ClosingBalance;

                    await Update(dayOpen);
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(dayOpenVM);
            }
        }
        #region API Calling

        [HttpGet]
        public async Task<IActionResult> GetActives()
        {
            string apiUrl = _config["ServerAddress:Address"] + $"/api/v1/dayopenings/getactives";
            var res = await ApiCalls<DayOpenings>.GetData(apiUrl);
            return Json(new
            {
                data = res
            });
        }
       
        [HttpGet]
        public async Task<DayOpenings> GetById(int Id)
        {
            string apiUrl = _config["ServerAddress:Address"] + $"/api/v1/dayopenings/{Id}";
            Task<DayOpenings> res;
            res = ApiCalls<DayOpenings>.GetById(apiUrl);
            return await res;
        }
        [HttpGet]
        public async Task<DayOpeningsSumVM> GetAllSums(int Id)
        {
            string apiUrl = _config["ServerAddress:Address"] + $"/api/v1/sumofalldayopening/{Id}";
            Task<DayOpeningsSumVM> res;
            res = ApiCalls<DayOpeningsSumVM>.GetById(apiUrl);
            return await res;
        }
        [HttpGet]
        public async Task<NewOpeningBalanceVM> GetNewOpeningBalance()
        {
            string apiUrl = _config["ServerAddress:Address"] + $"/api/v1/dayopenings/openingbalance";
            Task<NewOpeningBalanceVM> res;
            res = ApiCalls<NewOpeningBalanceVM>.GetSingleData(apiUrl);
            return await res;
        }
        #endregion
    }
}

ERPSystem/Areas/Accounts/Views/DayOpenings/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
@*<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />*@
<link href="~/sweetalert/Sweetalert.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="/files/bower_components/datatables.net-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" type="text/css" href="/files/assets/pages/data-table/css/buttons.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="/files/bower_components/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css">

<div class="card">
    <div class="card-header">
        <h5>Day Openings</h5>
        <div class="btn-group float-right">
            @*<a class="btn btn-primary nav-link text-white float-right" style="margin-bottom: 20px;" asp-area="Master" asp-controller="Items" asp-action="Upsert">New Item</a>*@
            <button type="button" class="btn btn-primary newBtn" data-toggle="modal" data-target=".bs-example-modal-lg" id="newItem">New Day Openings</button>
        </div>
    </div>
    <div class="card-block">
        <div class="row">
            <div class="table-responsive">
                <img src="~/images/loading.gif" style="
                            position: absolute;
                            top: 50px;
                            width: 100px;
                            left: 45%;
                    " />
                <table id="tblData" class="table table-striped table-bordered table-hover" style="width:100%">
                    <thead>
                        <tr>
                            <th>Sr. #</th>
                            <th>Opening</th>
                            <th>Opening Rs.</th>
                            <th>Closing</th>
                            <th>Closing Rs.</th>
                            <th>Sale</th>
                            <th>Purchase</th>
                            <th>Payment</th>
                            <th>Receipt</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
        
    </div>
</div>

@section Scripts{
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    @*<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>*@
<script src="~/sweetalert/sweetalert.js"></script>
    <!-- data-table js -->   
    <script src="/files/bower_components/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="/files/assets/pages/data-table/js/dataTables.bootstrap4.min.js"></script>
    <script src="/files/bower_components/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/files/bower_components/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js"></script>
    <script src="/files/assets/pages/data-table/js/data-table-custom.js"></script>


    <script src="~/js/Accounts/DayOpenings.js"></script>
}

ERPSystem/Areas/Accounts/Views/DayOpenings/Upsert.cshtml
@model Domain.ViewModel.Accounts.DayOpeningsViewModel
@{
    var title = (Model.dayopening.DayOpeningsId > 0) ? "Close Day" : "Save";
    title = title + "";
    ViewData["Title"] = title;

    Layout = null;// "~/Views/Shared/_Layout.cshtml";
    string readOnly = "";

    if(Model.dayopening.DayOpeningsId > 0)
    {
        /* $("#DateOpening").prop('readonly', false);*/
    }
    else
    {
        readOnly = "";
    }
}

<form asp-area="Accounts" asp-controller="DayOpenings" asp-action="Upsert"
      autocomplete="off"
      data-ajax="true"
      data-ajax-method="POST"
      data-ajax-begin="OnBegin"
      data-ajax-failure="OnFailure"
      data-ajax-success="OnSuccess(data)"
      data-ajax-complete="OnComplete">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group" hidden>
        <input asp-for="dayopening.DayOpeningsId" class="form-control" />
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label class="control-label">Date Opening</label>
                @if (Model.dayopening.DayOpeningsId > 0)
                {
                    <input id="DateOpening" asp-for="dayopening.DateTimeOpening" class="form-control form-control-sm" type="date" />
                }
                else
                {
                    <input id="DateOpening" asp-for="dayopening.DateTimeOpening" class="form-control form-control-sm currentDatePicker" type="date" />
                }
                <span asp-validation-for="dayopening.DateTimeOpening" class="text-danger"></span>
            </div>
        </div>
    </div>
    @{
        if (Model.dayopening.DayOpeningsId > 0)
        {
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">Date Closing</label>
                        <input id="accountCode" asp-for="dayopening.DateTimeClosing" class="form-control form-control-sm" type="date" />
                        <span asp-validation-for="dayopening.DateTimeClosing" class="text-danger"></span>
                    </div>
                </div>
                
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">Sales</label>
                        <input id="accountCode" asp-for="dayopening.sales" readonly class="form-control form-control-sm" lang="en" type="number" />
                        <span asp-validation-for="dayopening.sales" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">Purchase</label>
                        <input id="accountCode" asp-for="dayopening.Purchases" readonly class="form-control form-control-sm" lang="en" type="number" />
                        <span asp-validation-for="dayopening.Purchases" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">Cash Reciepts</label>
                        <input id="accountCode" asp-for="dayopening.cashReciepts" readonly class="form-control form-control-sm" lang="en" type="number" />
                        <span asp-validation-for="dayopening.cashReciepts" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">Cash Payments</label>
                        <input id="accountCode" asp-for="dayopening.cashPayments" readonly class="form-control form-control-sm" lang="en" type="number" />
                        <span asp-validation-for="dayopening.cashPayments" class="text-danger"></span>
                    </div>
 
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="dayopening.Notes" class="control-label"></label>
                        <textarea asp-for="dayopening.Notes" class="form-control form-control-sm" rows="3"></textarea>
                        <span asp-validation-for="dayopening.Notes" class="text-danger"></span>
                    </div>
                </div>
            </div>
        }
    }
    @if (Model.dayopening.closeStatus != true)    
    {
        <div class="form-group float-right">
            <input type="submit" value="@title" class="btn btn-primary" />
            <input type="reset" value="Clear" class="btn btn-danger" />
        </div>
    }
</form>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.js"></script>


<script src="~/js/Accounts/DayOpeningForm.js"></script>
<script type="text/javascript">

</script>