ERPSystem/Areas/Accounts/Controllers/MonthOpeningController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Common.Utilities;
using Domain.Entities;
using Domain.ViewModel.Accounts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;

namespace ERPSystem.Areas.Accounts.Controllers
{
    [Area("Accounts")]
    public class MonthOpeningController : Controller
    {
        [BindProperty]
        public MonthOpeningsViewModel monthOpenVM { get; set; }
        private readonly IConfiguration _config;
        public MonthOpeningController(IConfiguration config)
        {
            _config = config;
        }
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
        #region API Calling

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            string apiUrl = _config["ServerAddress:Address"] + $"/api/v1/monthopenings/getall";
            var res = await ApiCalls<MonthOpenings>.GetData(apiUrl);
            return Json(new
            {
                data = res
            });
        }
        [HttpGet]
        public async Task<IActionResult> GetActives()
        {
            string apiUrl = _config["ServerAddress:Address"] + $"/api/v1/monthopenings/getactives";
            var res = await ApiCalls<MonthOpenings>.GetData(apiUrl);
            return Json(new
            {
                data = res
            });
        }
        [HttpGet]
        public async Task<IActionResult> GetNonActives()
        {
            string apiUrl = _config["ServerAddress:Address"] + $"/api/v1/monthopenings/getnonactives";
            var res = await ApiCalls<MonthOpenings>.GetData(apiUrl);
            return Json(new
            {
                data = res
            });
        }
        [HttpPost]
        public async Task<bool> Create(MonthOpenings accC)
        {
            string apiUrl = _config["ServerAddress:Address"] + $"/api/v1/monthopenings/";
            var res = await ApiCalls<MonthOpenings>.Add(accC, apiUrl);
            return res;
        }
  
        [HttpGet]
        public async Task<MonthOpenings> GetById(int Id)
        {
            string apiUrl = _config["ServerAddress:Address"] + $"/api/v1/monthopenings/{Id}";
            Task<MonthOpenings> res;
            res = ApiCalls<MonthOpenings>.GetById(apiUrl);
            return await res;
        }
        [HttpGet]
        public async Task<IEnumerable<SelectListItem>> DropDownData()
        {
            try
            {
                string apiUrl = _config["ServerAddress:Address"] + $"/api/v1/monthopenings/dropdown/";
                string res = await ApiCalls<string>.GetDropDownList(apiUrl);
                List<SelectListItem> record = Newtonsoft.Json.JsonConvert.DeserializeObject<List<SelectListItem>>(res);
                return record;
            }
            catch (Exception ex)
            {

                throw;
            }
        }
        #endregion
    }
}

ERPSystem/Areas/Accounts/Views/MonthOpening /Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
otstrap4.min.css">
<div class="card">
    <div class="card-header">
        <h5>Month Openings</h5>
        <div class="btn-group float-right">
            @*<a class="btn btn-primary nav-link text-white float-right" style="margin-bottom: 20px;" asp-area="Master" asp-controller="Items" asp-action="Upsert">New Item</a>*@
            <button type="button" class="btn btn-primary newBtn" data-toggle="modal" data-target=".bs-example-modal-lg" id="newItem"><i aria-hidden="true" class="fa fa-pencil"></i>New Month Openings</button>
        </div>
    </div>
    <div class="card-block">
        <div class="table-responsive">
            <img src="~/images/loading.gif" style="
                            position: absolute;
                            top: 50px;
                            width: 100px;
                            left: 45%;
                    " />
            <table id="tblData" class="table table-striped table-bordered table-hover" style="width:100%">
                <thead>
                    <tr>
                        <th>Sr. #</th>
                        <th>Month</th>
                        <th>Date Opening</th>
                        <th>Opening Amount</th>                        
                        <th>Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>

    <!-- data-table js -->
    <script src="/files/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/files/bower_components/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/files/assets/pages/data-table/js/jszip.min.js"></script>  
    <script src="/files/assets/pages/data-table/js/data-table-custom.js"></script>


    <script src="~/js/Accounts/MonthOpenings.js"></script>
}

ERPSystem/Areas/Accounts/Views/MonthOpening /Upsert.cshtml
@model Domain.ViewModel.Accounts.MonthOpeningsViewModel
@{
    var title = (Model.monthopening.MonthOpeningsId > 0) ? "Close Month" : "Save";
    title = title + "";
    ViewData["Title"] = title;

    Layout = null;// "~/Views/Shared/_Layout.cshtml";
}

<form asp-area="Accounts" asp-controller="MonthOpening" asp-action="Upsert"
      autocomplete="off"
      data-ajax="true"
      data-ajax-method="POST"
      data-ajax-begin="OnBegin"
      data-ajax-failure="OnFailure"
      data-ajax-success="OnSuccess(data)"
      data-ajax-complete="OnComplete">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group" hidden>
        <input asp-for="monthopening.MonthOpeningsId" class="form-control" />
    </div>
    @if (Model.monthopening.MonthOpeningsId == 0)
    {
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label class="control-label">Date Opening</label>
                    <input id="accountCode" asp-for="monthopening.DateOpening" class="form-control form-control-sm currentDatePicker" type="date" />
                    <span asp-validation-for="monthopening.DateOpening" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label class="control-label">Opening Balance</label>
                    <input id="accountCode" asp-for="monthopening.OpeningBalance" class="form-control form-control-sm" type="number" />
                    <span asp-validation-for="monthopening.OpeningBalance" class="text-danger"></span>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="monthopening.Name" class="control-label"></label>
                    <input id="accountCode" asp-for="monthopening.Name" readonly class="form-control form-control-sm" />
                    <span asp-validation-for="monthopening.Name" class="text-danger"></span>
                </div>
            </div>           
            <div class="col-md-4">
                @{
                    if (Model.monthopening.MonthOpeningsId > 0)
                    {
                        <div class="form-group">
                            <label style="margin-top: 35px;">
                                Closed Status <input type="checkbox" id="accountCode" asp-for="monthopening.closeStatus" class="" />
                            </label>
                            <span asp-validation-for="monthopening.closeStatus" class="text-danger"></span>
                        </div>
                    }
                }
            </div>
        </div>       
    }
    <div class="form-group float-right">
        <input type="submit" value="@title" class="btn btn-primary" />
        <input type="reset" value="Clear" class="btn btn-danger" />
    </div>
</form>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/js/Accounts/MonthOpenings.js"></script>
<script type="text/javascript">

</script>