ERPSystem/Areas/Accounts/Controllers/ExpensesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Common.Utilities;
using Domain.Entities;
using Domain.ViewModel.Accounts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;

namespace ERPSystem.Areas.Accounts.Controllers
{
    [Area("Accounts")]
    public class ExpensesController : Controller
    {
        [BindProperty]
        public ExpensesViewModel expVM { get; set; }
        private readonly IConfiguration _config;
        public ExpensesController(IConfiguration config)
        {
            _config = config;
        }
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> Upsert(int? id)
        {
            expVM = new ExpensesViewModel();
            ViewBag.ExpenseHeads = await DropDownData();
            if (id != null)
            {
                var exps = await GetById((int)id);
                expVM.expenses.Name = exps.Name;
                expVM.expenses.ExpensesId = exps.ExpensesId;
                expVM.expenses.MonthOpeningsId = exps.MonthOpeningsId;
                expVM.expenses.Amount = exps.Amount;
                expVM.expenses.Notes = exps.Notes;
                expVM.expenses.date = exps.date;
                expVM.expenses.ExpenseHeadsId = exps.ExpenseHeadsId;
            }

            return View(expVM);
        }
     
        #region API Calling

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            string apiUrl = _config["ServerAddress:Address"] + $"/api/v1/expenses/getall";
            var res = await ApiCalls<ExpensesViewModel>.GetData(apiUrl);
            //await _serviceCaller.GetData(apiUrl);
            return Json(new
            {
                data = res
            });
        }    

        [HttpPost]
        public async Task<IActionResult> Create(Expenses accC)
        {
            string apiUrl = _config["ServerAddress:Address"] + $"/api/v1/expenses/";
            var res = await ApiCalls<Expenses>.Add(accC, apiUrl);
            return Json(new
            {
                data = res
            });
        }

        [HttpGet]
        public async Task<IEnumerable<SelectListItem>> DropDownData()
        {
            try
            {
                string apiUrl = _config["ServerAddress:Address"] + $"/api/v1/expenseheads/dropdown/";
                string res = await ApiCalls<string>.GetDropDownList(apiUrl);
                List<SelectListItem> record = Newtonsoft.Json.JsonConvert.DeserializeObject<List<SelectListItem>>(res);
                return record;
            }
            catch (Exception ex)
            {

                throw;
            }
        }
        #endregion
    }
}

ERPSystem/Areas/Accounts/Views/Expenses /Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />

<link rel="stylesheet" type="text/css" href="/files/bower_components/datatables.net-bs4/css/dataTables.bootstrap4.min.css">


<div class="card">
    <div class="card-header">
        <h5>Expenses</h5>
        <div class="btn-group float-right">
            @*<a class="btn btn-primary nav-link text-white float-right" style="margin-bottom: 20px;" asp-area="Master" asp-controller="Items" asp-action="Upsert">New Item</a>*@
            <button type="button" class="btn btn-primary newBtn" data-toggle="modal" data-target=".bs-example-modal-lg" id="newItem">New Expenses</button>
        </div>
    </div>
    <div class="card-block">
        <div class="table-responsive">
            <img src="~/images/loading.gif" style="
                            position: absolute;
                            top: 50px;
                            width: 100px;
                            left: 45%;
                    " />
            <table id="tblData" class="table table-striped table-bordered table-hover" style="width:100%">
                <thead>
                    <tr>
                        <th>Sr. #</th>
                        <th>Name</th>
                        <th>Amount</th>                 
                        <th>Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>

    <!-- data-table js -->
    <script src="/files/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/files/bower_components/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/files/assets/pages/data-table/js/jszip.min.js"></script>
    <script src="/files/assets/pages/data-table/js/pdfmake.min.js"></script>
    <script src="/files/assets/pages/data-table/js/vfs_fonts.js"></script>

    <script src="/files/assets/pages/data-table/js/data-table-custom.js"></script>

    <script src="~/js/Accounts/Expenses.js"></script>
}

ERPSystem/Areas/Accounts/Views/Expenses /Upsert.cshtml
@model Domain.ViewModel.Accounts.ExpensesViewModel
@{
    var title = (Model.expenses.ExpensesId > 0) ? "Update" : "Save";
    title = title + "";
    ViewData["Title"] = title;

    Layout = null;// "~/Views/Shared/_Layout.cshtml";
}
<form asp-area="Accounts" asp-controller="Expenses" asp-action="Upsert">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="form-group" hidden>
            <input asp-for="expenses.ExpensesId" class="form-control" />
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label class="control-label">Expense Head</label>
                <select id="AccountHead" class="form-control form-control-sm" asp-for="expenses.ExpenseHeadsId" asp-items="@ViewBag.ExpenseHeads">
                    <option>Select Expense Head </option>
                </select>
                <span asp-validation-for="expenses.ExpenseHeadsId" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label class="control-label">Date</label>
                <input id="accountCode" asp-for="expenses.date" class="form-control form-control-sm currentDatePicker" type="date" />
                <span asp-validation-for="expenses.date" class="text-danger"></span>
            </div>
        </div>
    </div>
</form>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.js"></script>

<script>
    $(document).ready(function () {
        $('.currentDatePicker').val(new Date().toDateInputValue());
    });
</script>